apiVersion: apps/v1
kind: Deployment
metadata:
  name: td-project-1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: td-project-1
  template:
    metadata:
      labels:
        app: td-project-1
    spec:
      containers:
        - name: app
          image: td-project-1-app
          ports:
            - containerPort: 5000