# Kubernetes Deployment for the Logistics Tracking App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-api-deployment
  namespace: logistics-prod
  labels:
    app: tracking-api
    tier: backend
spec:
  replicas: 3 # Running 3 copies for high availability
  selector:
    matchLabels:
      app: tracking-api
  template:
    metadata:
      labels:
        app: tracking-api
    spec:
      containers:
      - name: tracking-app
        # Using the secure image from Project 2
        image: ghcr.io/pink2026/my-secure-app:latest
        ports:
        - containerPort: 5000
        # Resource constraints to prevent cluster crashes (The "Business" fix)
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        # Liveness probe to auto-restart the app if it hangs
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10